name: React CI/CD Pipeline

# Trigger the pipeline on push to main branch or on pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from the repo

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Use Node.js version 18 (or match your project version)

    - name: Install dependencies
      run: npm install  # Install npm dependencies

    - name: Lint code
      run: npm run lint  # Lint the code to ensure coding standards

    - name: Run tests
      run: npm test  # Run tests (if you have them set up)

    - name: Build the app
      run: npm run build  # Build the React app using Vite

    # You can add a deploy step if you want to deploy the built app to a server
